#config_version=6
mode:
  start_events: random_available_mission_start
  stop_events: random_available_mission_stop, game_ended, ball_ended, game_ending, ball_ending
  priority: 5000
  restart_on_next_ball: false

###########################

event_player:
  mode_radio_started: random_available_mission_stop
  mode_charleston_started: random_available_mission_stop
  mode_speakeasy_started: random_available_mission_stop
  mode_cult_started: random_available_mission_stop
  mode_graveyard_started: random_available_mission_stop
  mode_city_started: random_available_mission_stop
  mode_aza_started: random_available_mission_stop
  mode_king_started: random_available_mission_stop
  mode_nyarla_started: random_available_mission_stop
  mode_cthulhu_started: random_available_mission_stop
  mode_shub_started: random_available_mission_stop

###########################

random_event_player:
  launch_random_mission_pick:
    - radio_start{current_player.mission_radio=='notcompleted'}
    - charleston_start{current_player.mission_charleston=='notcompleted'}
    - speakeasy_start{current_player.mission_speakeasy=='notcompleted'}
    - cult_start{current_player.mission_cult=='notcompleted'}
    - graveyard_start{current_player.mission_graveyard=='notcompleted'}
    - city_start{current_player.mission_city=='notcompleted'}
    - aza_start{current_player.azathoth_mission_available=='available'}
    - king_start{current_player.king_mission_available=='available'}
    - nyarla_start{current_player.nyarla_mission_available=='available'}
    - cthulhu_start{current_player.cthulhu_mission_available=='available'}
    - shub_start{current_player.shub_mission_available=='available'}

###########################

show_player:
  mode_random_available_mission_started:
    random_available_mission_show:
      speed: 40
      priority: 200
      loops: 0
      events_when_completed: launch_random_mission_pick

###########################

sound_player:
  mode_random_available_mission_started:
    random_mission_sound:
      action: play   